# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-14 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_url', models.CharField(max_length=256, verbose_name='产品url')),
                ('p_title', models.CharField(max_length=32, verbose_name='产品名称')),
                ('p_img', models.CharField(max_length=256, verbose_name='产品图片')),
                ('p_id', models.IntegerField(verbose_name='产品ID')),
                ('p_prices', models.CharField(blank=True, max_length=128, null=True, verbose_name='商品价格')),
                ('p_c_score', models.FloatField(blank=True, null=True, verbose_name='产品总评分')),
                ('p_comments', models.CharField(blank=True, max_length=128, null=True, verbose_name='产品评价')),
                ('p_c_all_nums', models.CharField(blank=True, max_length=256, null=True, verbose_name='概况点评内容')),
                ('p_c_time', models.CharField(blank=True, max_length=64, null=True, verbose_name='产品评论日期')),
                ('p_price_trend', models.CharField(blank=True, max_length=64, null=True, verbose_name='价格趋势')),
            ],
            options={
                'verbose_name_plural': '产品信息',
                'db_table': 'product_info',
            },
        ),
    ]
